//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAccessGroup_M
    {
        public int DocAccessGroupID { get; set; }
        public string AccessGroup { get; set; }
        public bool Active { get; set; }
    }
}
