//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentID { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
        public Nullable<int> DocumentRefID { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> DocCategoryID { get; set; }
        public Nullable<int> DocSubCategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> StakeholderID { get; set; }
        public string FileAttached { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public string DocumentManager { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string SpecifyLocation { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
    }
}
