//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DynamicControl()
        {
            this.DynamicControlValues = new HashSet<DynamicControlValue>();
        }
    
        public int ControlID { get; set; }
        public Nullable<int> ControlTypeID { get; set; }
        public string ControlName { get; set; }
    
        public virtual DynamicControlType DynamicControlType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynamicControlValue> DynamicControlValues { get; set; }
    }
}
