//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentSubOutcome_M
    {
        public int IncidentSubOutcomeID { get; set; }
        public Nullable<int> IncidentMainOutcomeID { get; set; }
        public string IncidentSubOutcome { get; set; }
        public Nullable<int> AnswerType { get; set; }
    
        public virtual IncidentMainOutcome_M IncidentMainOutcome_M { get; set; }
    }
}
