//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentSubRootCause_M
    {
        public int IncidentSubRootCauseID { get; set; }
        public Nullable<int> IncidentMainRootCauseID { get; set; }
        public string IncidentSubRootCause { get; set; }
        public Nullable<int> AnswerType { get; set; }
    
        public virtual IncidentMainRootCause_M IncidentMainRootCause_M { get; set; }
    }
}
