//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentDocument_T
    {
        public int IncidentDocumentID { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<System.Guid> DocGUID { get; set; }
    }
}
