//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_People_T
    {
        public int IncidentPeopleID { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> IncidentPeopleInvolvedID { get; set; }
        public Nullable<int> IncidentRelationID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsPatientInjured { get; set; }
        public string Nationality { get; set; }
        public string RegNo { get; set; }
        public string CVRNo { get; set; }
    
        public virtual IncidentPeopleInvolved_M IncidentPeopleInvolved_M { get; set; }
        public virtual IncidentRelation_M IncidentRelation_M { get; set; }
        public virtual Incident Incident { get; set; }
    }
}
