//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident_Interview_T
    {
        public int IncidentInterviewID { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public Nullable<int> InterviewerID { get; set; }
        public Nullable<int> IncidentPeopleID { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Details { get; set; }
    
        public virtual Users_M Users_M { get; set; }
    }
}
