//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentMainRootCause_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidentMainRootCause_M()
        {
            this.IncidentSubRootCause_M = new HashSet<IncidentSubRootCause_M>();
        }
    
        public int IncidentMainRootCauseID { get; set; }
        public string IncidentMainRootCause { get; set; }
        public bool Active { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentSubRootCause_M> IncidentSubRootCause_M { get; set; }
    }
}
