//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentSubOutcomeAnswer_T
    {
        public int SubOutcomeAnswerID { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public Nullable<int> IncidentSubOutcomeID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> AnswerTypeID { get; set; }
    }
}
