//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incident()
        {
            this.Incident_People_T = new HashSet<Incident_People_T>();
            this.RiskRegisters = new HashSet<RiskRegister>();
        }
    
        public int IncidentID { get; set; }
        public Nullable<int> EventTypeID { get; set; }
        public string IncidentNo { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public bool OnBehalfReporting { get; set; }
        public string ReporterName { get; set; }
        public string ReporterEmail { get; set; }
        public string ReporterDesignation { get; set; }
        public string ReporterBranch { get; set; }
        public string ReporterPhone { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public string Description { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> IncidentTypeID { get; set; }
        public Nullable<int> IncidentSubTypeID { get; set; }
        public bool Confidential { get; set; }
        public string InvestigationComments { get; set; }
        public string InvestigatorReport { get; set; }
        public string InvestigationConclusion { get; set; }
        public Nullable<int> IncidentFeedbackTypeID { get; set; }
        public string FeedbackComments { get; set; }
        public Nullable<System.Guid> IncidentGUID { get; set; }
        public bool Registered { get; set; }
        public Nullable<System.DateTime> RegisteredOn { get; set; }
        public Nullable<System.DateTime> IncidentCreatedDate { get; set; }
        public string Outcome { get; set; }
        public string RemedialAction { get; set; }
        public Nullable<int> IncidentStatusID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public bool CreatorCanComment { get; set; }
        public Nullable<int> HarmScoreID { get; set; }
        public string RootCauseAnalysis { get; set; }
        public bool RiskAnalysisRequired { get; set; }
        public Nullable<bool> RiskAnalysisCompleted { get; set; }
        public Nullable<bool> ReOpened { get; set; }
        public string ReOpenRemarks { get; set; }
        public Nullable<int> FeedbackTypeID { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> InvestigationDueDate { get; set; }
    
        public virtual Branch_M Branch_M { get; set; }
        public virtual EventType_SM EventType_SM { get; set; }
        public virtual IncidentFeedbackType_M IncidentFeedbackType_M { get; set; }
        public virtual IncidentHarmScore_M IncidentHarmScore_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident_People_T> Incident_People_T { get; set; }
        public virtual IncidentPriorities_M IncidentPriorities_M { get; set; }
        public virtual IncidentStatus_M IncidentStatus_M { get; set; }
        public virtual Location_M Location_M { get; set; }
        public virtual Users_M Users_M { get; set; }
        public virtual IncidentSubTypes_M IncidentSubTypes_M { get; set; }
        public virtual IncidentTypes_M IncidentTypes_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskRegister> RiskRegisters { get; set; }
    }
}
