//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentSubTypes_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidentSubTypes_M()
        {
            this.Incidents = new HashSet<Incident>();
        }
    
        public int IncidentSubTypeID { get; set; }
        public Nullable<int> IncidentTypeID { get; set; }
        public Nullable<int> IncidentPriorityID { get; set; }
        public string IncidentSubType { get; set; }
        public bool Active { get; set; }
        public bool RiskAssessment { get; set; }
        public string Comments { get; set; }
    
        public virtual IncidentPriorities_M IncidentPriorities_M { get; set; }
        public virtual IncidentTypes_M IncidentTypes_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
    }
}
