//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidents_MainRootCause_T
    {
        public int IncidentMRCID { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public Nullable<int> IncidentMainRootCauseID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Answered { get; set; }
    }
}
