//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleUser_V
    {
        public int TaskPeopleID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string RegNo { get; set; }
        public string CVRNo { get; set; }
        public string Name2 { get; set; }
        public string Phone { get; set; }
        public string Designation { get; set; }
        public string TaskRelation { get; set; }
        public string TaskPeopleInvolved { get; set; }
    }
}
