//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskRegister
    {
        public int RiskRegisterID { get; set; }
        public Nullable<int> RRNo { get; set; }
        public string RiskRegisterNo { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool Proactive { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public Nullable<int> RiskCategoryID { get; set; }
        public Nullable<int> RiskCostID { get; set; }
        public Nullable<int> RiskDescriptorID { get; set; }
        public Nullable<int> RiskStatusID { get; set; }
        public Nullable<int> RiskStrategyID { get; set; }
        public string Controlsinplace { get; set; }
        public string Adequacy { get; set; }
        public int RARating { get; set; }
        public string RARiskLevel { get; set; }
        public Nullable<int> RARiskProbabilityID { get; set; }
        public Nullable<int> RASeverityID { get; set; }
        public int RRRating { get; set; }
        public string RRRiskLevel { get; set; }
        public Nullable<int> RRRiskProbabilityID { get; set; }
        public Nullable<int> RRSeverityID { get; set; }
        public string FutureStrategies { get; set; }
        public string PotentialRiskFactors { get; set; }
        public string Comments { get; set; }
        public string Description { get; set; }
        public Nullable<int> RiskAssessedByID { get; set; }
        public Nullable<int> RiskOwnerID { get; set; }
        public string TaskNo { get; set; }
        public Nullable<int> RiskKeyStatusID { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> RiskRegisteredDate { get; set; }
    
        public virtual Incident Incident { get; set; }
        public virtual RiskCategory_M RiskCategory_M { get; set; }
        public virtual RiskCost_M RiskCost_M { get; set; }
        public virtual RiskDescriptor_M RiskDescriptor_M { get; set; }
        public virtual RiskKeyStatus_T RiskKeyStatus_T { get; set; }
        public virtual RiskProbability_M RiskProbability_M { get; set; }
        public virtual RiskProbability_M RiskProbability_M1 { get; set; }
        public virtual RiskStatus_M RiskStatus_M { get; set; }
        public virtual RiskStrategy_M RiskStrategy_M { get; set; }
        public virtual Users_M Users_M { get; set; }
    }
}
