//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAssessorUser_V
    {
        public int RiskAssessorID { get; set; }
        public Nullable<int> RiskID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
    }
}
