//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskLevel_M2
    {
        public int RiskLevelID { get; set; }
        public string RiskLevel { get; set; }
        public string ActionTimeScale { get; set; }
        public string ReviewTimeScale { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
    }
}
