//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskKeyStatusDates_T
    {
        public int RiskKeyStatusDateID { get; set; }
        public Nullable<int> RiskRegisterID { get; set; }
        public Nullable<int> RiskKeyStatusID { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    }
}
