//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskProbability_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskProbability_M()
        {
            this.RiskRegisters = new HashSet<RiskRegister>();
            this.RiskRegisters1 = new HashSet<RiskRegister>();
        }
    
        public int RiskProbabilityID { get; set; }
        public Nullable<int> RiskFrequencyScoreID { get; set; }
        public string RiskProbability { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
    
        public virtual RiskFrequencyScore_M RiskFrequencyScore_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskRegister> RiskRegisters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskRegister> RiskRegisters1 { get; set; }
    }
}
