//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_People_T
    {
        public int TaskPeopleID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> TaskPeopleInvolvedID { get; set; }
        public Nullable<int> TaskRelationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string IdentityNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string RegNo { get; set; }
        public string CVRNo { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual TaskPeopleInvolved_M TaskPeopleInvolved_M { get; set; }
        public virtual TaskRelation_M TaskRelation_M { get; set; }
        public virtual Task Task { get; set; }
    }
}
