//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSubCategory_M
    {
        public int TaskSubCategoryID { get; set; }
        public Nullable<int> TaskCategoryID { get; set; }
        public string SubCategory { get; set; }
        public bool Active { get; set; }
    
        public virtual TaskCategory_M TaskCategory_M { get; set; }
    }
}
