//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskRelation_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskRelation_M()
        {
            this.Task_People_T = new HashSet<Task_People_T>();
        }
    
        public int TaskRelationID { get; set; }
        public string TaskRelation { get; set; }
        public string Comments { get; set; }
        public bool SendEmail { get; set; }
        public string EmailSubject { get; set; }
        public string EmailHeader { get; set; }
        public string EmailFooter { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_People_T> Task_People_T { get; set; }
    }
}
