//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskIndex_V
    {
        public int Expr1 { get; set; }
        public string Priority { get; set; }
        public string TaskCategory { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool Expr2 { get; set; }
        public Nullable<System.DateTime> Expr3 { get; set; }
        public Nullable<int> Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public Nullable<int> Expr8 { get; set; }
        public Nullable<int> Expr9 { get; set; }
        public string Expr10 { get; set; }
        public string Expr11 { get; set; }
        public Nullable<System.DateTime> Expr12 { get; set; }
        public Nullable<System.DateTime> Expr13 { get; set; }
        public Nullable<System.DateTime> Expr14 { get; set; }
        public Nullable<int> Expr15 { get; set; }
        public string Expr16 { get; set; }
        public string Expr17 { get; set; }
        public string Owner { get; set; }
        public string TriggeredBy { get; set; }
        public string Expr18 { get; set; }
        public Nullable<int> Expr19 { get; set; }
        public int TaskID { get; set; }
        public bool Registered { get; set; }
        public Nullable<System.DateTime> Registeredon { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public string ReferenceNo { get; set; }
        public string TaskNo { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string AssignedTo { get; set; }
        public string TaskCost { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> TaskStatusID { get; set; }
        public string OwnerNote { get; set; }
        public string Description { get; set; }
        public string Feedback { get; set; }
        public string ProviderName { get; set; }
        public string Location { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public string SubCategory { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<decimal> Progress { get; set; }
        public string FeedbackType { get; set; }
        public Nullable<System.DateTime> TaskDueDate { get; set; }
    }
}
