//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatusUser_V
    {
        public string TaskStatus { get; set; }
        public int TaskStatusID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int Task_StatusID { get; set; }
        public string Name { get; set; }
    }
}
