//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskComment_V
    {
        public int CommentID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CommentDateTime { get; set; }
        public string Comment { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
    }
}
