//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_M()
        {
            this.Incident_Interview_T = new HashSet<Incident_Interview_T>();
            this.Incidents = new HashSet<Incident>();
            this.RiskAssessors_T = new HashSet<RiskAssessors_T>();
            this.RiskRegisters = new HashSet<RiskRegister>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
        public string LicenseNo { get; set; }
        public string EmployeeNo { get; set; }
        public string EmailID { get; set; }
    
        public virtual Branch_M Branch_M { get; set; }
        public virtual Department_M Department_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident_Interview_T> Incident_Interview_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> Incidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskAssessors_T> RiskAssessors_T { get; set; }
        public virtual UserRole_SM UserRole_SM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskRegister> RiskRegisters { get; set; }
    }
}
